# Generated by Django 3.1.2 on 2020-12-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.BigIntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('Subject_1', models.CharField(max_length=40)),
                ('Subject_1_marks', models.IntegerField(default=0)),
                ('Subject_2', models.CharField(max_length=40)),
                ('Subject_2_marks', models.IntegerField(default=0)),
                ('Subject_3', models.CharField(max_length=40)),
                ('Subject_3_marks', models.IntegerField(default=0)),
                ('Subject_4', models.CharField(max_length=40)),
                ('Subject_4_marks', models.IntegerField(default=0)),
                ('Subject_5', models.CharField(max_length=40)),
                ('Subject_5_marks', models.IntegerField(default=0)),
                ('marksheet', models.FileField(default='', upload_to='exams/marksheet')),
            ],
        ),
    ]
