# Generated by Django 3.1.2 on 2020-12-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marksheet',
            field=models.FileField(blank=True, default='', upload_to='exams/marksheet'),
        ),
    ]
