<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-11-08 05:05
=======
# Generated by Django 3.1.2 on 2020-11-08 04:30
>>>>>>> 68a286a713f5cad9365a6da968a5d107e185c2c7

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=60)),
                ('desc', models.CharField(default='', max_length=70)),
                ('found_date', models.DateField()),
                ('item_pic', models.ImageField(default='', upload_to='lostitems/images')),
            ],
        ),
    ]
