# Generated by Django 3.1.2 on 2020-12-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=60)),
                ('topic', models.CharField(default='', max_length=70)),
                ('pic', models.ImageField(default='', upload_to='notes/images')),
                ('pdf_file', models.FileField(upload_to='notes/pdf')),
            ],
        ),
    ]
