# Generated by Django 3.1.2 on 2020-12-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAANotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_name', models.CharField(default='', max_length=50)),
                ('notes_sub', models.CharField(default='', max_length=50)),
                ('notes_image', models.ImageField(blank=True, null=True, upload_to='notes/images')),
                ('pub_date', models.DateTimeField(null=True)),
                ('notes_document', models.FileField(blank=True, null=True, upload_to='notes/images')),
            ],
        ),
        migrations.CreateModel(
            name='DSDNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_name', models.CharField(default='', max_length=50)),
                ('notes_sub', models.CharField(default='', max_length=50)),
                ('notes_image', models.ImageField(blank=True, null=True, upload_to='notes/images')),
                ('pub_date', models.DateTimeField(null=True)),
                ('notes_document', models.FileField(blank=True, null=True, upload_to='notes/images')),
            ],
        ),
        migrations.CreateModel(
            name='NoteSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_teacher', models.CharField(default='', max_length=50)),
                ('notes_subject', models.CharField(default='', max_length=50)),
                ('notes_subinshort', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
